name: node-flow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Set up database
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
        run: |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS test_db;"
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} test_db < ./path/to/your/schema.sql

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_NAME: test_db
        run: npm test

