name: node-flow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo mysqladmin -u root password "${{ secrets.DB_PASSWORD }}"

      - name: Configure MySQL
        run: |
          sudo mysql --user=root --password="${{ secrets.DB_PASSWORD }}" <<EOF
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_PASSWORD }}';
          FLUSH PRIVILEGES;
          CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};
          GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          FLUSH PRIVILEGES;
          EOF

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm test