name: node-flow

on:
  pull_request:
    branches:
        - main
        
jobs:
    build:
       runs-on: ubuntu-latest

       steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: checkout version and install
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: install dependencies
          run: npm install

        - name: Run tests
          env:
            NODE_ENV: test
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}           
            DB_DIALECT: ${{ secrets.DB_DIALECT }}    
          run: npm test


        

