name: node-flow

on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL to Start
        run: |
          echo "Waiting for MySQL to start..."
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            sleep 1
          done
          echo "MySQL is up and running!"

      - name: Create Database
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS healthDB;"

      - name: Verify Database Creation
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"

      - name: Run Integration Tests
        env:
          SQL_PSWD: "${{ secrets.SQL_PSWD_TEST }}"
          DATABASE: "healthDB"
          DIALECT: "mysql"
          SQL_USER: "${{ secrets.SQL_USER_TEST }}"
          HOST: 127.0.0.1
        run: npm run test:integration