name: node-flow

on:
  pull_request:
    branches:
        - main
        
jobs:
    build:
       runs-on: ubuntu-latest

       steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: checkout version and install
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: pr failing
          run : exit 1

        - name: install dependencies
          run: npm install


        

