name: WebApp-Workflow

on:
  pull_request: 
    branches:
      - main

jobs:
  build:
    name: WebApp Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install MySQL & Start Service
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Secure MySQL Installation & Set Root Password
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Set up environment variables
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DIALECT: ${{ secrets.DIALECT }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "DATABASE_HOST=$DATABASE_HOST" >> .env
          echo "DATABASE_NAME=$DATABASE_NAME" >> .env
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
          echo "DATABASE_PORT=$DATABASE_PORT" >> .env
          echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
          echo "DIALECT=$DIALECT" >> .env
          echo "PORT=$PORT" >> .env
          cat .env

      - name: Grant Privileges (Corrected and Secure)
        run: |
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS \`${{ secrets.DATABASE_NAME }}\`;"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ secrets.DATABASE_USERNAME }}'@'localhost' IDENTIFIED BY '${{ secrets.DATABASE_PASSWORD }}';"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON \`${{ secrets.DATABASE_NAME }}\`.* TO '${{ secrets.DATABASE_USERNAME }}'@'localhost';"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"

      - name: Install Dependencies
        run: |
          cd src
          npm install
      
      - name: Run Tests
        working-directory: src
        run: npm test