name: node-flow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt install -y mysql-server
          
          # Ensure MySQL directory exists
          sudo mkdir -p /var/run/mysqld
          sudo chown -R mysql:mysql /var/run/mysqld
          
          # Start MySQL service
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Fix MySQL Authentication
        run: |
          echo "Updating MySQL root authentication..."
          sudo systemctl stop mysql
          sudo mysqld_safe --skip-grant-tables --skip-networking & sleep 5
          sudo mysql -uroot <<EOF
          FLUSH PRIVILEGES;
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_PASSWORD }}';
          FLUSH PRIVILEGES;
          EOF
          sudo systemctl restart mysql
          sleep 5  

      - name: Verify MySQL Connection
        run: |
          mysql -uroot -p"${{ secrets.DB_PASSWORD }}" -e "SHOW DATABASES;"

      - name: Create MySQL Database and User
        run: |
          mysql -uroot -p"${{ secrets.DB_PASSWORD }}" <<EOF
          CREATE DATABASE IF NOT EXISTS \`${{ secrets.DB_NAME }}\`;
          CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          GRANT ALL PRIVILEGES ON \`${{ secrets.DB_NAME }}\`.* TO '${{ secrets.DB_USER }}'@'localhost';
          FLUSH PRIVILEGES;
          EOF

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm test