name: Packer status check workflow

on:
  pull_request:
    branches:
      - main
 
jobs:
  test:
    name: Packer Workflow
    runs-on: ubuntu-latest
    env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
        DB_LOGGING: ${{ secrets.DB_LOGGING }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SERVER_PORT: ${{ secrets.SERVER_PORT}}
        AWS_DEMO_ACCOUNT_ID: ${{ secrets.AWS_DEMO_ACCOUNT_ID }}
        GCP_DEMO_PROJECT_ID: ${{ secrets.GCP_DEMO_PROJECT_ID }}
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP with creds
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify GCP Authentication
        run: gcloud auth list

 
      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Create webapp.zip from existing directory
        run: |
          zip -r webapp.zip .
        shell: bash

      - name: Prepare Packer Files
        run: |
          mkdir -p AMI/files  
          mv webapp.zip AMI/files/  

      - name: Initialize packer
        working-directory: AMI
        run: |
          packer init csye-packer.pkr.hcl
        shell: bash
        
 
      - name: Format packer
        working-directory: AMI
        run: |
          packer fmt -check csye-packer.pkr.hcl
        continue-on-error: false
        shell: bash
        
      - name: Validate Packer
        working-directory: AMI
        run: |
          packer validate csye-packer.pkr.hcl
        shell: bash